// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0zKcrDCdjY3lV_HuIoljR6n1sC5W6aDQ',
    appId: '1:1029128518658:web:a96240dcb276330ced3b1b',
    messagingSenderId: '1029128518658',
    projectId: 'fsapp-232b7',
    authDomain: 'fsapp-232b7.firebaseapp.com',
    storageBucket: 'fsapp-232b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRz_8WRwEZ_OYhcDh5p93aewS5vDX7h2k',
    appId: '1:1029128518658:android:2d9daff892438b4eed3b1b',
    messagingSenderId: '1029128518658',
    projectId: 'fsapp-232b7',
    storageBucket: 'fsapp-232b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeqZ1M-MSLp8dDOvKIPA9XyG7LQ25EET4',
    appId: '1:1029128518658:ios:0d47f9964e7ed5b0ed3b1b',
    messagingSenderId: '1029128518658',
    projectId: 'fsapp-232b7',
    storageBucket: 'fsapp-232b7.firebasestorage.app',
    iosBundleId: 'com.example.fsappPolfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeqZ1M-MSLp8dDOvKIPA9XyG7LQ25EET4',
    appId: '1:1029128518658:ios:0d47f9964e7ed5b0ed3b1b',
    messagingSenderId: '1029128518658',
    projectId: 'fsapp-232b7',
    storageBucket: 'fsapp-232b7.firebasestorage.app',
    iosBundleId: 'com.example.fsappPolfer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0zKcrDCdjY3lV_HuIoljR6n1sC5W6aDQ',
    appId: '1:1029128518658:web:bde989a644b46f02ed3b1b',
    messagingSenderId: '1029128518658',
    projectId: 'fsapp-232b7',
    authDomain: 'fsapp-232b7.firebaseapp.com',
    storageBucket: 'fsapp-232b7.firebasestorage.app',
  );
}
